# Generated by Django 5.1.4 on 2025-01-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='transaction_receipts/'),
        ),
    ]
