# Generated by Django 5.1.4 on 2025-02-10 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investapp', '0002_transaction_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('return_type', models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Variable')], max_length=8)),
                ('fixed_return_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Required if return type is Fixed', max_digits=5, null=True)),
                ('min_return_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Required if return type is Variable', max_digits=5, null=True)),
                ('max_return_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Required if return type is Variable', max_digits=5, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
