# Generated by Django 5.1.4 on 2025-02-10 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investapp', '0004_userdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentproject',
            name='user',
        ),
        migrations.CreateModel(
            name='UserProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_percentage', models.DecimalField(decimal_places=2, help_text='Custom return percentage for this user in this project', max_digits=5)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users', to='investapp.investmentproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'project')},
            },
        ),
    ]
