# Generated by Django 5.1.4 on 2025-02-10 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investapp', '0005_remove_investmentproject_user_userprojectassignment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprojectassignment',
            unique_together=set(),
        ),
    ]
