# Generated by Django 5.1.4 on 2025-02-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investapp', '0006_alter_userprojectassignment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprojectassignment',
            name='return_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom return percentage for this user in this project', max_digits=5, null=True),
        ),
    ]
